// Auto-generated by CLI – Adjust this interface to match the raw API shape
export interface RawItem {
  // TODO: Describe the fields returned by the API
  // id: string;
}

export type RawApiResponse = RawItem[] | Record<string, any>;
